dataset_paths:
    train_data: /home/ph/datasets/left_ventricle_volume/train/ 
    train_labels: /home/ph/datasets/left_ventricle_volume/train.csv
    validation_data: /home/ph/datasets/left_ventricle_volume/validation/
    sample_submission: /Users/Breakend/Documents/datasets/sciencebowl2015/sample_submission_validate.csv
